(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"myPions-Pion-Nucleon",
  Authors -> {""},
  Version -> "",
  Date -> "",
  Institutions -> {""},
  Emails -> {""}};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], Proton -> F[7], Neutron -> F[8], H -> S[1], G0 -> S[2], GP -> S[3], Pi0 -> S[4], PiP -> S[5], Eta -> S[6], K0 -> S[7], Kp -> S[8], DeltaPP -> R[Null], DeltaP -> R[Null], Delta0 -> R[Null], DeltaM -> R[Null]};

FR$InteractionOrderPerturbativeExpansion={{QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[IsoSpin] ] = Range[ 2 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

IndexRange[ Index[IsoVector] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {BaryonNumber, Q, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MNucleon,
    Indices -> {},
    PropagatorLabel -> "Proton" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {BaryonNumber, 0, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MNucleon,
    Indices -> {},
    PropagatorLabel -> "Neutron" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPi,
    Indices -> {},
    PropagatorLabel -> "Pi0" },

S[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MPi,
    Indices -> {},
    PropagatorLabel -> "PiP" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MEta,
    Indices -> {},
    PropagatorLabel -> "Eta" },

S[7] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MK0,
    Indices -> {},
    PropagatorLabel -> "K0" },

S[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MKp,
    Indices -> {},
    PropagatorLabel -> "Kp" },

R[Null] == {
    SelfConjugate -> False,
    QuantumNumbers -> {2*Q, BaryonNumber, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDelta,
    Indices -> {},
    PropagatorLabel -> "DeltaPP" },

R[Null] == {
    SelfConjugate -> False,
    QuantumNumbers -> {2*Q, BaryonNumber, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDelta,
    Indices -> {},
    PropagatorLabel -> "DeltaPP" },

R[Null] == {
    SelfConjugate -> False,
    QuantumNumbers -> {2*Q, BaryonNumber, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDelta,
    Indices -> {},
    PropagatorLabel -> "DeltaPP" },

R[Null] == {
    SelfConjugate -> False,
    QuantumNumbers -> {2*Q, BaryonNumber, Y},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDelta,
    Indices -> {},
    PropagatorLabel -> "DeltaPP" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ F[7] ] = GaugeXi[F[3]];
GaugeXi[ F[8] ] = GaugeXi[F[4]];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[6] ] = GaugeXi[S[7]];
GaugeXi[ S[7] ] = GaugeXi[S[8]];
GaugeXi[ S[8] ] = GaugeXi[S[9]];
GaugeXi[ R[Null] ] = GaugeXi[R[1]];
GaugeXi[ R[Null] ] = GaugeXi[R[1]];
GaugeXi[ R[Null] ] = GaugeXi[R[1]];
GaugeXi[ R[Null] ] = GaugeXi[R[1]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MNucleon[ ___ ] := MNucleon;
MH[ ___ ] := MH;
MPi[ ___ ] := MPi;
MEta[ ___ ] := MEta;
MK0[ ___ ] := MK0;
MKp[ ___ ] := MKp;
MDelta[ ___ ] := MDelta;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{0, 0}, {(-2*I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}},

C[ S[5] , -S[5] , V[1] ] == {{I*EL, 0}, {(-I)*EL, 0}},

C[ S[4] , S[4] , S[5] , -S[5] ] == {{0, 0}, {0, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {0, 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{0, 0}, {(-2*I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-I)/fPi^2, 0}, {(-2*I)/fPi^2, 0}},

C[ -F[7] , F[7] , V[1] ] == {{I*EL, 0}, {I*EL, 0}},

C[ -F[8] , F[8] , S[5] , -S[5] , V[1] ] == {{((I/2)*EL)/fPi^2, 0}, {((I/2)*EL)/fPi^2, 0}},

C[ -F[8] , F[8] , S[5] , -S[5] ] == {{(I/4)/fPi^2, 0}, {(I/4)/fPi^2, 0}, {(-1/4*I)/fPi^2, 0}, {(-1/4*I)/fPi^2, 0}},

C[ -F[4] , F[4] , S[1] ] == {{((-I)*ye)/Sqrt[2], 0}, {((-I)*ye)/Sqrt[2], 0}, {0, 0}, {0, 0}},

C[ -F[5] , F[5] , S[1] ] == {{((-I)*ym)/Sqrt[2], 0}, {((-I)*ym)/Sqrt[2], 0}, {0, 0}, {0, 0}},

C[ -F[6] , F[6] , S[1] ] == {{((-I)*ytau)/Sqrt[2], 0}, {((-I)*ytau)/Sqrt[2], 0}, {0, 0}, {0, 0}},

C[ -F[8] , F[7] , S[4] , -S[5] , V[1] ] == {{((I/2)*EL)/(Sqrt[2]*fPi^2), 0}, {((I/2)*EL)/(Sqrt[2]*fPi^2), 0}},

C[ -F[8] , F[7] , S[4] , -S[5] ] == {{(I/2)/(Sqrt[2]*fPi^2), 0}, {(I/2)/(Sqrt[2]*fPi^2), 0}, {(-1/2*I)/(Sqrt[2]*fPi^2), 0}, {(-1/2*I)/(Sqrt[2]*fPi^2), 0}},

C[ -F[7] , F[8] , S[4] , S[5] , V[1] ] == {{((I/2)*EL)/(Sqrt[2]*fPi^2), 0}, {((I/2)*EL)/(Sqrt[2]*fPi^2), 0}},

C[ -F[7] , F[8] , S[4] , S[5] ] == {{(-1/2*I)/(Sqrt[2]*fPi^2), 0}, {(-1/2*I)/(Sqrt[2]*fPi^2), 0}, {(I/2)/(Sqrt[2]*fPi^2), 0}, {(I/2)/(Sqrt[2]*fPi^2), 0}},

C[ -F[7] , F[7] , S[5] , -S[5] , V[1] ] == {{((-1/2*I)*EL)/fPi^2, 0}, {((-1/2*I)*EL)/fPi^2, 0}},

C[ -F[7] , F[7] , S[5] , -S[5] ] == {{(-1/4*I)/fPi^2, 0}, {(-1/4*I)/fPi^2, 0}, {(I/4)/fPi^2, 0}, {(I/4)/fPi^2, 0}},

C[ -S[5] , V[1] , V[3] ] == {{(EL^2*fPi)/(2*sw), 0}},

C[ S[4] , -S[5] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[4] , S[4] , -S[5] , V[1] , V[3] ] == {{-1/2*EL^2/(fPi*sw), 0}},

C[ S[5] , -S[5] , -S[5] , V[1] , V[3] ] == {{-(EL^2/(fPi*sw)), 0}},

C[ S[4] , -S[5] , V[3] ] == {{((-1/2*I)*EL)/sw, 0}, {((I/2)*EL)/sw, 0}},

C[ S[4] , S[4] , -S[5] , V[3] ] == {{-1/2*EL/(fPi*sw), 0}, {-1/2*EL/(fPi*sw), 0}, {EL/(2*fPi*sw), 0}},

C[ S[5] , -S[5] , -S[5] , V[3] ] == {{-(EL/(fPi*sw)), 0}, {0, 0}, {0, 0}},

C[ -F[7] , F[8] , V[3] ] == {{((I/2)*EL*(1 + ga))/(Sqrt[2]*sw), 0}, {((-1/2*I)*EL*(-1 + ga))/(Sqrt[2]*sw), 0}},

C[ -F[8] , F[8] , -S[5] , V[3] ] == {{(EL*(1 + ga))/(4*fPi*sw), 0}, {-1/4*(EL*(-1 + ga))/(fPi*sw), 0}},

C[ -F[8] , F[8] , S[4] , -S[5] , V[3] ] == {{((-1/8*I)*EL*(1 + ga))/(fPi^2*sw), 0}, {((I/8)*EL*(-1 + ga))/(fPi^2*sw), 0}},

C[ -F[8] , F[7] , -S[5] , -S[5] , V[3] ] == {{((I/2)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((-1/2*I)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[7] , F[8] , S[4] , V[3] ] == {{(EL*(1 + ga))/(2*Sqrt[2]*fPi*sw), 0}, {-1/2*(EL*(-1 + ga))/(Sqrt[2]*fPi*sw), 0}},

C[ -F[7] , F[8] , S[4] , S[4] , V[3] ] == {{((-1/2*I)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((I/2)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[7] , F[8] , S[5] , -S[5] , V[3] ] == {{((-1/4*I)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((I/4)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[7] , F[7] , -S[5] , V[3] ] == {{-1/4*(EL*(1 + ga))/(fPi*sw), 0}, {(EL*(-1 + ga))/(4*fPi*sw), 0}},

C[ -F[7] , F[7] , S[4] , -S[5] , V[3] ] == {{((I/8)*EL*(1 + ga))/(fPi^2*sw), 0}, {((-1/8*I)*EL*(-1 + ga))/(fPi^2*sw), 0}},

C[ S[5] , V[1] , -V[3] ] == {{-1/2*(EL^2*fPi)/sw, 0}},

C[ S[4] , S[5] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[4] , S[4] , S[5] , V[1] , -V[3] ] == {{EL^2/(2*fPi*sw), 0}},

C[ S[5] , S[5] , -S[5] , V[1] , -V[3] ] == {{EL^2/(fPi*sw), 0}},

C[ S[4] , S[5] , -V[3] ] == {{((I/2)*EL)/sw, 0}, {((-1/2*I)*EL)/sw, 0}},

C[ S[4] , S[4] , S[5] , -V[3] ] == {{-1/2*EL/(fPi*sw), 0}, {-1/2*EL/(fPi*sw), 0}, {EL/(2*fPi*sw), 0}},

C[ S[5] , S[5] , -S[5] , -V[3] ] == {{0, 0}, {0, 0}, {-(EL/(fPi*sw)), 0}},

C[ -F[8] , F[7] , -V[3] ] == {{((I/2)*EL*(1 + ga))/(Sqrt[2]*sw), 0}, {((-1/2*I)*EL*(-1 + ga))/(Sqrt[2]*sw), 0}},

C[ -F[8] , F[8] , S[5] , -V[3] ] == {{-1/4*(EL*(1 + ga))/(fPi*sw), 0}, {(EL*(-1 + ga))/(4*fPi*sw), 0}},

C[ -F[8] , F[8] , S[4] , S[5] , -V[3] ] == {{((-1/8*I)*EL*(1 + ga))/(fPi^2*sw), 0}, {((I/8)*EL*(-1 + ga))/(fPi^2*sw), 0}},

C[ -F[8] , F[7] , S[4] , -V[3] ] == {{-1/2*(EL*(1 + ga))/(Sqrt[2]*fPi*sw), 0}, {(EL*(-1 + ga))/(2*Sqrt[2]*fPi*sw), 0}},

C[ -F[8] , F[7] , S[4] , S[4] , -V[3] ] == {{((-1/2*I)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((I/2)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[8] , F[7] , S[5] , -S[5] , -V[3] ] == {{((-1/4*I)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((I/4)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[7] , F[8] , S[5] , S[5] , -V[3] ] == {{((I/2)*EL*(1 + ga))/(Sqrt[2]*fPi^2*sw), 0}, {((-1/2*I)*EL*(-1 + ga))/(Sqrt[2]*fPi^2*sw), 0}},

C[ -F[7] , F[7] , S[5] , -V[3] ] == {{(EL*(1 + ga))/(4*fPi*sw), 0}, {-1/4*(EL*(-1 + ga))/(fPi*sw), 0}},

C[ -F[7] , F[7] , S[4] , S[5] , -V[3] ] == {{((I/8)*EL*(1 + ga))/(fPi^2*sw), 0}, {((-1/8*I)*EL*(-1 + ga))/(fPi^2*sw), 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[4] , S[4] , S[4] , S[4] , V[3] , -V[3] ] == {{(((3*I)/2)*EL^2)/(fPi^2*sw^2), 0}},

C[ S[4] , S[4] , S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2)/(fPi^2*sw^2), 0}},

C[ S[5] , S[5] , -S[5] , -S[5] , V[3] , -V[3] ] == {{(I*EL^2)/(fPi^2*sw^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , S[4] , S[4] , V[2] ] == {{-1/2*(EL*(cw^2 + sw^2))/(cw*fPi*sw), 0}, {-1/2*(EL*(cw^2 + sw^2))/(cw*fPi*sw), 0}, {-1/2*(EL*(cw^2 + sw^2))/(cw*fPi*sw), 0}},

C[ S[4] , S[5] , -S[5] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*fPi*sw), 0}, {-1/2*(EL*(cw^2 + sw^2))/(cw*fPi*sw), 0}, {-1/2*(EL*(cw^2 + sw^2))/(cw*fPi*sw), 0}},

C[ S[5] , -S[5] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ -F[8] , F[8] , V[2] ] == {{((-1/4*I)*EL*(1 + ga)*(cw^2 + sw^2))/(cw*sw), 0}, {((I/4)*EL*(-1 + ga)*(cw^2 + sw^2))/(cw*sw), 0}},

C[ -F[7] , F[7] , V[2] ] == {{((I/4)*EL*(cw^2*(1 + ga) + (-3 + ga)*sw^2))/(cw*sw), 0}, {((-1/4*I)*EL*(cw^2*(-1 + ga) + (3 + ga)*sw^2))/(cw*sw), 0}},

C[ -F[8] , F[8] , S[5] , -S[5] , V[2] ] == {{((I/4)*EL*(cw^2*(1 + ga) + (-1 + ga)*sw^2))/(cw*fPi^2*sw), 0}, {((-1/4*I)*EL*(cw^2*(-1 + ga) + (1 + ga)*sw^2))/(cw*fPi^2*sw), 0}},

C[ -F[8] , F[7] , -S[5] , V[2] ] == {{(EL*(cw^2*(1 + ga) - (-1 + ga)*sw^2))/(2*Sqrt[2]*cw*fPi*sw), 0}, {(EL*(-(cw^2*(-1 + ga)) + (1 + ga)*sw^2))/(2*Sqrt[2]*cw*fPi*sw), 0}},

C[ -F[8] , F[7] , S[4] , -S[5] , V[2] ] == {{((I/4)*EL*(cw^2*(1 + ga) + (-1 + ga)*sw^2))/(Sqrt[2]*cw*fPi^2*sw), 0}, {((-1/4*I)*EL*(cw^2*(-1 + ga) + (1 + ga)*sw^2))/(Sqrt[2]*cw*fPi^2*sw), 0}},

C[ -F[7] , F[8] , S[5] , V[2] ] == {{(-(cw^2*EL*(1 + ga)) + EL*(-1 + ga)*sw^2)/(2*Sqrt[2]*cw*fPi*sw), 0}, {(EL*(cw^2*(-1 + ga) - (1 + ga)*sw^2))/(2*Sqrt[2]*cw*fPi*sw), 0}},

C[ -F[7] , F[8] , S[4] , S[5] , V[2] ] == {{((I/4)*EL*(cw^2*(1 + ga) + (-1 + ga)*sw^2))/(Sqrt[2]*cw*fPi^2*sw), 0}, {((-1/4*I)*EL*(cw^2*(-1 + ga) + (1 + ga)*sw^2))/(Sqrt[2]*cw*fPi^2*sw), 0}},

C[ -F[7] , F[7] , S[5] , -S[5] , V[2] ] == {{((-1/4*I)*EL*(cw^2*(1 + ga) + (-1 + ga)*sw^2))/(cw*fPi^2*sw), 0}, {((I/4)*EL*(cw^2*(-1 + ga) + (1 + ga)*sw^2))/(cw*fPi^2*sw), 0}},

C[ -S[5] , V[3] , V[2] ] == {{-1/2*(EL^2*fPi)/cw, 0}},

C[ S[4] , -S[5] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[4] , S[4] , -S[5] , V[3] , V[2] ] == {{EL^2/(2*cw*fPi), 0}},

C[ S[5] , -S[5] , -S[5] , V[3] , V[2] ] == {{EL^2/(cw*fPi), 0}},

C[ S[5] , -V[3] , V[2] ] == {{(EL^2*fPi)/(2*cw), 0}},

C[ S[4] , S[5] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[4] , S[4] , S[5] , -V[3] , V[2] ] == {{-1/2*EL^2/(cw*fPi), 0}},

C[ S[5] , S[5] , -S[5] , -V[3] , V[2] ] == {{-(EL^2/(cw*fPi)), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , S[4] , S[4] , S[4] , V[2] , V[2] ] == {{(((3*I)/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*fPi^2*sw^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{(-2*I)*EL^2, 0}},

C[ S[4] , S[4] , S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*fPi^2*sw^2), 0}},

C[ S[5] , S[5] , -S[5] , -S[5] , V[2] , V[2] ] == {{(I*EL^2*(cw^2 + sw^2)^2)/(cw^2*fPi^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[4] , F[4] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[5] , F[5] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[6] , F[6] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[1] , F[4] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}},

C[ -F[5] , F[5] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}},

C[ -F[6] , F[6] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}},

C[ -F[8] , F[8] , S[4] ] == {{0, 0}, {0, 0}, {ga/(2*fPi), 0}, {-1/2*ga/fPi, 0}},

C[ -F[8] , F[7] , -S[5] , V[1] ] == {{(EL*ga)/(Sqrt[2]*fPi), 0}, {-((EL*ga)/(Sqrt[2]*fPi)), 0}},

C[ -F[8] , F[7] , -S[5] ] == {{0, 0}, {0, 0}, {-(ga/(Sqrt[2]*fPi)), 0}, {ga/(Sqrt[2]*fPi), 0}},

C[ -F[7] , F[8] , S[5] , V[1] ] == {{-((EL*ga)/(Sqrt[2]*fPi)), 0}, {(EL*ga)/(Sqrt[2]*fPi), 0}},

C[ -F[7] , F[8] , S[5] ] == {{0, 0}, {0, 0}, {-(ga/(Sqrt[2]*fPi)), 0}, {ga/(Sqrt[2]*fPi), 0}},

C[ -F[7] , F[7] , S[4] ] == {{0, 0}, {0, 0}, {-1/2*ga/fPi, 0}, {ga/(2*fPi), 0}}

}

